name: Release

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Upload to Release
      uses: Shopify/upload-to-release@v2.0.0
      with:
        name: pod
        path: ./target/release/pod
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  build-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Upload to Release
      uses: Shopify/upload-to-release@v2.0.0
      with:
        name: pod.exe
        path: ./target/release/pod.exe
        repo-token: ${{ secrets.GITHUB_TOKEN }}
