name: Release

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Upload to Release
      uses: JasonEtco/upload-to-release@v0.1.1
      with:
          args: ./target/release/pod
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Upload to Release
      uses: JasonEtco/upload-to-release@v0.1.1
      with:
          args: ./target/release/pod.exe
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}}
